question_data = [{"category":"General Knowledge","difficulty":"easy","question":"Video streaming website YouTube was purchased in it's entirety by Facebook for US$1.65 billion in stock.","correct_answer":"False","incorrect_answers":["True"]},
  {"category":"General Knowledge","difficulty":"easy","question":"Gumbo is a stew that originated in Louisiana.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"medium","question":"Furby was released in 1998.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"medium","question":"There are 86400 seconds in a day.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"hard","question":"&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"easy","question":"The Sun rises from the North.","correct_answer":"False","incorrect_answers":["True"]},
  {"category":"General Knowledge","difficulty":"easy","question":"On average, at least 1 person is killed by a drunk driver in the United States every hour.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"medium","question":"Kissing someone for one minute burns about 2 calories.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"easy","question":"Pluto is a planet.","correct_answer":"False","incorrect_answers":["True"]},
  {"category":"General Knowledge","difficulty":"easy","question":"Adolf Hitler was born in Australia. ","correct_answer":"False","incorrect_answers":["True"]},
  {"category":"General Knowledge","difficulty":"medium","question":"The French word for &quot;glass&quot; is &quot;glace&quot;.","correct_answer":"False","incorrect_answers":["True"]},
  {"category":"General Knowledge","difficulty":"hard","question":"In Scandinavian languages, the letter &Aring; means river.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"easy","question":"&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"hard","question":"Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"medium","question":"The scientific name for the Southern Lights is Aurora Australis?","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"easy","question":"The National Animal of Scotland is the Unicorn.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"medium","question":"Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.","correct_answer":"False","incorrect_answers":["True"]},
  {"category":"General Knowledge","difficulty":"easy","question":"A pasodoble is a type of Italian pasta sauce.","correct_answer":"False","incorrect_answers":["True"]},
  {"category":"General Knowledge","difficulty":"medium","question":"Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.","correct_answer":"True","incorrect_answers":["False"]},
  {"category":"General Knowledge","difficulty":"hard","question":"NCIS stands for &quot;Navy Corps Investigative Service&quot;","correct_answer":"False","incorrect_answers":["True"]}]